[[headers]]
    for = "/*"
    [headers.values]
        content-security-policy = "base-uri 'none'; default-src 'self'; object-src 'none'; upgrade-insecure-requests;"
        cross-origin-embedder-policy = "require-corp"
        cross-origin-opener-policy = "same-origin"
        cross-origin-resource-policy = "same-origin"
        x-content-type-options = "nosniff"
        x-frame-options = "deny"